# Generated by Django 2.2 on 2021-07-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semitvshows_app', '0009_auto_20210727_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
